-- MySQL Script generated by MySQL Workbench
-- mié 11 jul 2018 17:32:59 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Liga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Liga` (
  `Pais` VARCHAR(45) NULL,
  `Id_Liga` INT NOT NULL,
  `Division` VARCHAR(45) NULL,
  `Cant_descensos` INT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Liga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipo` (
  `Id_Equipo` INT NOT NULL,
  `Liga` INT NOT NULL,
  `Fundacion` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Equipo`),
  INDEX `fk_Equipo_Liga_idx` (`Liga` ASC),
  CONSTRAINT `fk_Equipo_Liga`
    FOREIGN KEY (`Liga`)
    REFERENCES `mydb`.`Liga` (`Id_Liga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jugador` (
  `Dni` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Posicion` VARCHAR(45) NULL,
  `Sueldo` VARCHAR(45) NULL,
  `Fecha_nac` VARCHAR(45) NULL,
  `Nacionalidad` VARCHAR(45) NULL,
  `Equipo` INT NOT NULL,
  PRIMARY KEY (`Dni`),
  INDEX `fk_Jugador_Equipo1_idx` (`Equipo` ASC),
  CONSTRAINT `fk_Jugador_Equipo1`
    FOREIGN KEY (`Equipo`)
    REFERENCES `mydb`.`Equipo` (`Id_Equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DT` (
  `Dni` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Sueldo` VARCHAR(45) NULL,
  `Fecha_nac` VARCHAR(45) NULL,
  `Nacionalidad` VARCHAR(45) NULL,
  `Equipo` INT NOT NULL,
  PRIMARY KEY (`Dni`),
  INDEX `fk_DT_Equipo1_idx` (`Equipo` ASC),
  CONSTRAINT `fk_DT_Equipo1`
    FOREIGN KEY (`Equipo`)
    REFERENCES `mydb`.`Equipo` (`Id_Equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Liga`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Liga` (`Pais`, `Id_Liga`, `Division`, `Cant_descensos`, `Nombre`) VALUES ('Argentina', 1, 'Primera', 6, 'Superliga');
INSERT INTO `mydb`.`Liga` (`Pais`, `Id_Liga`, `Division`, `Cant_descensos`, `Nombre`) VALUES ('España', 2, 'Primera', 3, 'LaLiga');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Equipo`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Equipo` (`Id_Equipo`, `Liga`, `Fundacion`, `Nombre`) VALUES (1, 1, '1995/10/01', 'Aldosivi');
INSERT INTO `mydb`.`Equipo` (`Id_Equipo`, `Liga`, `Fundacion`, `Nombre`) VALUES (2, 2, '1890/01/02', 'Farselona');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Jugador`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Jugador` (`Dni`, `Nombre`, `Apellido`, `Posicion`, `Sueldo`, `Fecha_nac`, `Nacionalidad`, `Equipo`) VALUES (1234, 'Paquete', 'Busquets', 'MCD', '0', '16/7/1988 ', 'España', 2);
INSERT INTO `mydb`.`Jugador` (`Dni`, `Nombre`, `Apellido`, `Posicion`, `Sueldo`, `Fecha_nac`, `Nacionalidad`, `Equipo`) VALUES (1235, 'Diego', 'Villar', 'MCO', '€12.000', '25/4/1981', 'Argentina', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`DT`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`DT` (`Dni`, `Nombre`, `Apellido`, `Sueldo`, `Fecha_nac`, `Nacionalidad`, `Equipo`) VALUES (1234, 'Gustavo', 'Alvarez', '5000', '4/7/1948', 'Argentina', 1);
INSERT INTO `mydb`.`DT` (`Dni`, `Nombre`, `Apellido`, `Sueldo`, `Fecha_nac`, `Nacionalidad`, `Equipo`) VALUES (1235, 'Ernesto', 'Valverde', '2,5M', '9/2/1964', 'España', 2);

COMMIT;

